# Default values for lmsfrontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of pod replicas
replicaCount: 1

# Container Image Configuration
image:
  repository: laxmikant93/lmsfrontend
  pullPolicy: IfNotPresent
  tag: v1

# Service Configuration
service:
  type: LoadBalancer  # Correct capitalization
  port: 8085
  targetPort: http # Ensure this matches the named port in deployment.yaml

# Resource Requests and Limits
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

# Additional Labels to be added to Kubernetes resources
additionalLabels:
  environment: production
  team: devops
  version: "1.0.0"

# Uncomment and configure the following sections if needed

# Liveness and Readiness Probes
# livenessProbe:
#   httpGet:
#     path: /
#     port: http
#   initialDelaySeconds: 30
#   periodSeconds: 10
# readinessProbe:
#   httpGet:
#     path: /
#     port: http
#   initialDelaySeconds: 5
#   periodSeconds: 10

# Image Pull Secrets (Not needed for public images)
# imagePullSecrets:
#   - name: your-secret-name

# Service Account Configuration (Not needed for basic deployments)
# serviceAccount:
#   create: true
#   name: ""

# Pod Annotations and Labels
# podAnnotations: {}
# podLabels: {}

# Pod Security Context (Not needed for basic deployments)
# podSecurityContext:
#   fsGroup: 2000

# Container Security Context (Not needed for basic deployments)
# securityContext:
#   capabilities:
#     drop:
#       - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

# Horizontal Pod Autoscaling Configuration (Not enabled)
# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 1
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# Volumes and Volume Mounts (Not needed for basic deployments)
# volumes: []
# volumeMounts: []

# Node Selector (Not needed for basic deployments)
# nodeSelector: {}

# Tolerations (Not needed for basic deployments)
# tolerations: []

# Affinity (Not needed for basic deployments)
# affinity: {}
