apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-goauth
  labels:
    app.kubernetes.io/name: goauth
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type | title }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: goauth
    app.kubernetes.io/instance: {{ .Release.Name }}
